# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('seqid', models.IntegerField(default=0)),
                ('jlptlevel', models.IntegerField(choices=[(5, 'JLPT_N5'), (4, 'JLPT_N4'), (3, 'JLPT_N3'), (2, 'JLPT_N2'), (1, 'JLPT_N1'), (0, 'JLPT_N1P')], default=5)),
                ('level', models.IntegerField(default=0)),
                ('summary', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=12)),
                ('pronunciation', models.CharField(max_length=12)),
                ('kanaclass', models.IntegerField(choices=[(1, 'KATAKANA'), (0, 'HIRAGANA')], default=0)),
                ('kanatype', models.IntegerField(choices=[(2, 'DAKUTEN'), (1, 'COMBO'), (0, 'BASE')], default=0)),
                ('description', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatternFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('entry', models.ManyToManyField(to='languagebits.GrammarEntry')),
            ],
        ),
        migrations.CreateModel(
            name='PatternItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('formula', models.ManyToManyField(to='languagebits.PatternFormula')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('furigana', models.CharField(default='', max_length=140)),
                ('romanji', models.CharField(max_length=140)),
                ('pos', models.IntegerField(choices=[(0, 'NOUN'), (1, 'VERB'), (2, 'I_ADJ'), (3, 'NA_ADJ')], default=0)),
                ('definition', models.CharField(max_length=140)),
                ('seqid', models.IntegerField(default=0)),
                ('jlptlevel', models.IntegerField(choices=[(5, 'JLPT_N5'), (4, 'JLPT_N4'), (3, 'JLPT_N3'), (2, 'JLPT_N2'), (1, 'JLPT_N1'), (0, 'JLPT_N1P')], default=5)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='grammardescription',
            name='entry',
            field=models.ManyToManyField(to='languagebits.GrammarEntry'),
        ),
    ]
