"""
Django settings for japan_project project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&u&_@l#0f^+k^ygad&rw(tg8e64cto1$n0s#%cblo0&r@_!vxd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.0.12', 'luiseduardo8899.hopto.org']


# Application definition

INSTALLED_APPS = [
    'premiumaccount.apps.PremiumaccountConfig',
    'teacher.apps.TeacherConfig',
    'userinfo.apps.UserinfoConfig',
    'dictionary.apps.DictionaryConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #all-auth required apps 
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    #include the providers you want to enable
    #'allauth.socialaccount.providers.google',
    #'allauth.socialaccount.providers.baidu',
    'allauth.socialaccount.providers.facebook',
    'payments',
    'haystack',
]

#HAYSTACK_CONNECTIONS = {
#    'default': {
#        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
#        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
#    },
#}

#SOLR - Haystack connection
HAYSTACK_CONNECTIONS = {
    "default": {
        "ENGINE": "haystack.backends.solr_backend.SolrEngine",
#<TODO>        "URL": "http://127.0.0.1:8983/solr/japan_core"
        "URL": "http://luiseduardo8899.hopto.org:8983/solr/japan_core"
    },
    # ... other settings ...
}

SITE_ID=1 #from `allauth` setup documentation. Allows manytomany association between sites powered by same Django installation

#Directory to upload media files, pictures, videos
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#+++++++ Start : Payments App Configuration +++++++++++++++
PAYMENT_HOST = 'luiseduardo8899.hopto.org:8000'
PAYMENT_USES_SSL = False
PAYMENT_MODEL = 'premiumaccount.Payment'
PAYMENT_VARIANTS = {
    'default': ('payments.dummy.DummyProvider', {})}
#+++++++ End : Payments App Configuration +++++++++++++++

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/hello/'
LOGOUT_REDIRECT_URL = '/byebye/'
ROOT_URLCONF = 'japan_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'sitewide', 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'japan_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#<DEFAULT>DATABASES = {
#<DEFAULT>    'default': {
#<DEFAULT>        'ENGINE': 'django.db.backends.sqlite3',
#<DEFAULT>        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#<DEFAULT>    }
#<DEFAULT>}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'jpdb',
        'USER': 'jpdb_user',
        'PASSWORD': '$UperArc#',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
